config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :caisses
  resources :group_coefficients
  resources :open_days
  resources :history_administrative_groups
  resources :history_physical_groups
  resources :absences
  resources :reasons
  resources :students
  get 'physical_groups/stats' => 'physical_groups#stats'
  get 'physical_groups/parameters' => 'group_coefficients#index'
  resources :physical_groups
  get 'physical_groups/:id/absences' => 'physical_groups#absences'
  get 'administrative_groups/stats' => 'administrative_groups#stats'
  get 'administrative_groups/parameters' => 'group_coefficients#index'
  get '/justifications' => 'justifications#index'
  resources :administrative_groups
  root 'presence#index'
  get 'about' => 'about#index'

  get 'today' => 'presence#absents_du_jour'
  get 'today_email' => 'presence#absents_du_jour_email'

  resource :user_sessions, only: [:create, :new, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :physical_group
  belongs_to :administrative_group
  belongs_to :caisse
  has_many :absences
  has_many :history_physical_groups
  has_many :history_administrative_groups
  validates :last_name, :first_name, :physical_group_id, :administrative_group_id, :presence => true

  after_create {
    HistoryPhysicalGroup.create student_id: self.id, physical_group_id: self.physical_group_id, date_in: self.date_in
    HistoryAdministrativeGroup.create student_id: self.id, administrative_group_id: self.administrative_group_id, date_in: self.date_in
  }

  def age
  	now = Time.now.utc.to_date
    if self.birth_date
      dob = self.birth_date
    	return now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    else
      return nil
    end
  end

  def name
    return "#{self.last_name.upcase} #{self.first_name.split.map(&:capitalize).join(' ')}"
  end

  def absences_by_month(month, year, administrative_group_id=nil, physical_group_id=nil)
    start_date = Date.parse("01/#{month}/#{year}")
    end_date = start_date + 1.month - 1.day
    nb = 0
    if administrative_group_id
      nb = Absence.where("date >= ? and date <= ? and student_id = ? and administrative_group_id = ? and absence = ?",
                        start_date,
                        end_date,
                        self.id,
                        administrative_group_id,
                        true).count
    elsif physical_group_id
      nb = Absence.where("date >= ? and date <= ? and student_id = ? and physical_group_id = ? and absence = ?",
                        start_date,
                        end_date,
                        self.id,
                        physical_group_id,
                        true).count
    else
      nb = Absence.where("date >= ? and date <= ? and student_id = ? and absence = ?",
                        start_date,
                        end_date,
                        self.id,
                        true).count
    end
    return nb
  end

  def last_physical_group
    return HistoryPhysicalGroup.where(student_id: self.id).order(:date_in).last
  end

  def last_administrative_group
    return HistoryAdministrativeGroup.where(student_id: self.id).order(:date_in).last
  end

  def physical_group_at(date)
    return HistoryPhysicalGroup.where(student_id: self.id, physical_group_id: self.physical_group_id).where("date_in <= ? AND (date_out >= ? OR date_out IS NULL)", date, date).order(:date_in).last
  end

  def administrative_group_at(date)
    return HistoryAdministrativeGroup.where(student_id: self.id, administrative_group_id: self.administrative_group_id).where("date_in <= ? AND (date_out >= ? OR date_out IS NULL)", date, date).order(:date_in).last
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_groups, only: [:new, :create, :edit]

  # GET /students
  # GET /students.json
  def index
    @students = Student.order(:last_name, :first_name)
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @absences_injustifiees = Absence.joins(:reason).where(student_id: @student.id).where("reasons.title=?", "?").order("date DESC")
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.administrative_group_id = params["administrative_group"] if params["administrative_group"]
    @student.physical_group_id = params["physical_group"] if params["physical_group"]
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    def set_groups
      @administrative_groups = AdministrativeGroup.order(:title)
      @physical_groups = PhysicalGroup.order(:title)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :birth_date, :roomer, :physical_group_id, :administrative_group_id, :date_in, :secu_number, :sex, :caisse_id, :coef)
    end
end

app/helpers/students_helper.rb
module StudentsHelper

  def sex(s)
    result = ""
    if s
      result = "Homme" if s.upcase=='M'
      result = "Femme" if s.upcase=='F'
    end
    return result
  end

end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Prénom et nom de l'usager"><i class="fa fa-user fa-fw"></i></span>
        <%= f.text_field :first_name, class: "control-group", placeholder: "Prénom" %>
        <%= f.text_field :last_name, class: "control-group", placeholder: "Nom" %>
      </div>
  	</div>
    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Date de naissance"><i class="fa fa-calendar fa-fw"></i></span>
        <%= f.text_field :birth_date, class: "control-group", placeholder: "Date de naissance", value: @student.birth_date ? @student.birth_date.strftime("%d/%m/%Y") : "" %>
      </div>
    </div>

    <% unless @student.id %>
      <div class="control-group">
    	  <div class="field input-group">
    			<span class="input-group-addon" title="Groupe administratif"><i class="fa fa-university fa-fw"></i></span>
          <%= f.select(:administrative_group_id, [], {}, {class: "form-control"}) do %>
      			<% @administrative_groups.each do |group| %>
      				<%= content_tag(:option, group.title, value: group.id, selected: (group.id==@student[:administrative_group_id])) %>
      			<% end %>
      		<% end %>
        </div>
      </div>
      <div class="control-group">
    	  <div class="field input-group">
    			<span class="input-group-addon" title="Groupe physique"><i class="fa fa-group fa-fw"></i></span>
          <%= f.select(:physical_group_id, [], {}, {class: "form-control"}) do %>
      			<% @physical_groups.each do |group| %>
      				<%= content_tag(:option, group.title, value: group.id, selected: (group.id==@student[:physical_group_id])) %>
      			<% end %>
      		<% end %>
        </div>
      </div>
      <div class="control-group">
    			<div class="field input-group">
    				<span class="input-group-addon" title="Date d'entrée"><i class="fa fa-calendar fa-fw"></i></span>
            <%= f.date_field :date_in, class: "form-control", placeholder: "Date de naissance", value: Date.today.strftime("%d/%m/%Y") %>
          </div>
      </div>
    <% end %>

    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Pensionnaire"><i class="fa fa-bed fa-fw"></i></span>
        <div class="form-control">
          <%= f.label :roomer do %>
            <%= f.check_box :roomer %>
            Pensionnaire
          <% end %>
        </div>
      </div>
    </div>

    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Sexe"><i class="fa fa-venus-mars fa-fw"></i></span>
        <%= f.select(:sex, [], {}, class: "form-control") do %>
          <%= content_tag(:option, "", value: nil) %>
          <%= content_tag(:option, "Femme", value: "F", selected: (@student.sex=="F")) %>
          <%= content_tag(:option, "Homme", value: "M", selected: (@student.sex=="M")) %>
        <% end %>
      </div>
  	</div>

    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Taux de présence prévu"><b>%</b></span>
        <%= f.text_field :coef, class: "form-control", placeholder: "Taux de présence prévu (taux par défaut si vide)" %>
      </div>
  	</div>

    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Numéro de sécurité sociale"><i class="fa fa-credit-card fa-fw"></i></span>
        <%= f.text_field :secu_number, class: "form-control", placeholder: "Numéro de sécurité sociale" %>
      </div>
  	</div>
  </div>
  <div class="col-md-11">
    <div class="control-group">
  	  <div class="field input-group">
  			<span class="input-group-addon" title="Caisse de sécurité sociale"><i class="fa fa-stethoscope fa-fw"></i></span>
        <%= f.select(:caisse_id, [], {}, class: "form-control") do %>
          <%= content_tag(:option, "", value: nil) %>
          <% Caisse.order(:title).each do |caisse| %>
            <%= content_tag(:option, caisse.title, value: caisse.id, selected: (@student.caisse_id==caisse.id)) %>
          <% end %>
        <% end %>
      </div>
    </div>
	</div>
  <div class="col-md-1">
    <%= link_to new_caiss_path(student: @student.id), title: "Ajouter une nouvelle caisse", class: "form-control" do %>
      <i class="fa fa-pencil fa-fw"></i>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit t('Validate'), :class => 'btn btn-primary' %> ou
    <%= link_to 'Retour', :back %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="titre_actif">
  <h1>Modifier un usager</h1>
</div>

<%= render 'form' %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<div class="titre_actif">
  <h1>Liste des usagers</h1>
</div>

<div id="toolbar1">
  <%= link_to t('New Student'), new_student_path, class: "btn btn-primary" %>
</div>

<table id="table1"
  data-toolbar="#toolbar1"
  data-search="true"
  data-show-columns="true"
  data-show-export="true"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-page-list="[10, 25, 50, 100, ALL]"
  data-show-footer="false"
  data-toggle="table">
  <thead>
    <tr>
      <th data-align="left" data-valign="middle">Nom et prénom</th>
      <th data-align="center" data-valign="middle">Sexe</th>
      <th data-align="center" data-valign="middle">Date de naissance</th>
      <th data-align="center" data-valign="middle">age</th>
      <th data-field="operate" data-align="center">Groupe physique</th>
      <th data-align="center">Groupe administratif</th>
      <th data-align="center">Pensionnaire</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student %></td>
        <% if student.sex=="M" %>
          <td><i class="fa fa-mars fa-fw"></i></td>
        <% elsif student.sex=="F" %>
          <td><i class="fa fa-venus fa-fw"></i></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= student.birth_date ? student.birth_date.strftime("%d/%m/%Y") : "" %></td>
        <td><%= student.birth_date ? student.age : "" %></td>
        <td><%= link_to student.physical_group.title, student.physical_group %></td>
        <td><%= link_to student.administrative_group.title, student.administrative_group %></td>
        <% if student.roomer %>
          <td><i class="fa fa-bed fa-fw"></i></td>
        <% else %>
          <td>-</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<div class="titre_actif">
  <h1>Nouvel usager</h1>
</div>

<%= render 'form' %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<div class="titre_actif">
  <h1><%= @student.name %></h1>
</div>

<div class="col-md-6">
  <%= image_tag "student.png", class: "img-responsive", align: "right"  %>
</div>
<div class="col-md-6">
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Date de naissance"><i class="fa fa-calendar fa-fw"></i></span>
      <div class="control-paragraph"><%= @student.birth_date ? @student.birth_date.strftime("%d/%m/%Y") : "" %></div>
    </div>
	</div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Age"><i class="fa fa-birthday-cake fa-fw"></i></span>
      <div class="control-paragraph"><%= @student.age %> ans</div>
    </div>
	</div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Groupe administratif"><i class="fa fa-university fa-fw"></i></span>
      <% last_group = @student.last_administrative_group %>
      <div class="control-paragraph"><%= link_to last_group.administrative_group.title, last_group.administrative_group if last_group %>
        <span class="grey">depuis le <%= last_group.date_in.strftime("%d/%m/%Y") if last_group %></span>
        <%= link_to new_history_administrative_group_path(student: @student.id), title: "Changer de groupe administratif" do %>
          <i class="fa fa-pencil fa-fw"></i>
        <% end %>
      </div>
    </div>
	</div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Groupe physique"><i class="fa fa-group fa-fw"></i></span>
      <% last_group = @student.last_physical_group %>
      <div class="control-paragraph"><%= link_to last_group.physical_group.title, last_group.physical_group if last_group %>
        <span class="grey">depuis le <%= last_group.date_in.strftime("%d/%m/%Y") if last_group%></span>
        <%= link_to new_history_physical_group_path(student: @student.id), title: "Changer de groupe physique" do %>
          <i class="fa fa-pencil fa-fw"></i>
        <% end %>
      </div>
    </div>
	</div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Pensionnaire"><i class="fa fa-bed fa-fw"></i></span>
      <div class="control-paragraph"><%= @student.roomer ? "oui" : "non" %></div>
    </div>
	</div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Sexe"><i class="fa fa-venus-mars fa-fw"></i></span>
      <div class="control-paragraph"><%= sex(@student.sex) %></div>
    </div>
	</div>
  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon" title="Taux de présence prévu"><b>%</b></span>
      <div class="control-paragraph"><span class="<%= @student.coef ? '' : 'grey' %>"><%= @student.coef ? @student.coef : "Taux par défaut" %></span></div>
    </div>
  </div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Numéro de sécurité sociale"><i class="fa fa-credit-card fa-fw"></i></span>
      <div class="control-paragraph"><%= @student.secu_number %></div>
    </div>
	</div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Caisse de sécurité sociale"><i class="fa fa-stethoscope fa-fw"></i></span>
      <div class="control-paragraph"><%= @student.caisse.title if @student.caisse %></div>
    </div>
	</div>
  <br/>
  <div>
    <%= link_to t('Edit'), edit_student_path(@student), class: 'btn btn-primary' %>
  </div>
</div>

<% if @absences_injustifiees.count>0 %>
  <div class="col-md-12">
    <div class="cadre_bleu">
      <h2>Absences à justifier</h2>
    </div>

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Groupe</th>
          <th>Matin</th>
          <th>Après-midi</th>
          <th>Soir</th>
        </tr>
      </thead>

      <tbody>
        <% @absences_injustifiees.each do |absence| %>
          <tr onclick="window.document.location='/absences/'+<%= absence.id %>+'/edit';">
            <td><%= absence.date.strftime("%d/%m/%Y") %></td>
            <td><%= absence.physical_group.title %></td>
            <td><%= absence.morning ? "X" : "" %></td>
            <td><%= absence.afternoon ? "X" : "" %></td>
            <td><%= absence.night ? "X" : "" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>