config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :caisses
  resources :group_coefficients
  resources :open_days
  resources :history_administrative_groups
  resources :history_physical_groups
  resources :absences
  resources :reasons
  resources :students
  get 'physical_groups/stats' => 'physical_groups#stats'
  get 'physical_groups/parameters' => 'group_coefficients#index'
  resources :physical_groups
  get 'physical_groups/:id/absences' => 'physical_groups#absences'
  get 'administrative_groups/stats' => 'administrative_groups#stats'
  get 'administrative_groups/parameters' => 'group_coefficients#index'
  get '/justifications' => 'justifications#index'
  resources :administrative_groups
  root 'presence#index'
  get 'about' => 'about#index'

  get 'today' => 'presence#absents_du_jour'
  get 'today_email' => 'presence#absents_du_jour_email'

  resource :user_sessions, only: [:create, :new, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/history_administrative_group.rb
class HistoryAdministrativeGroup < ActiveRecord::Base
  belongs_to :student
  belongs_to :administrative_group
  validates :student_id, :administrative_group_id, :date_in, :presence => true

  before_create {
    last_history = self.student.last_administrative_group
    if last_history
      last_history.date_out = self.date_in-1
      last_history.save
    end
  }

  after_create {
    self.student.administrative_group_id = self.administrative_group_id
    self.student.save
  }
end

app/controllers/history_administrative_groups_controller.rb
class HistoryAdministrativeGroupsController < ApplicationController
  before_action :set_history_administrative_group, only: [:show, :edit, :update, :destroy]
  before_action :set_groups, only: [:new, :edit]

  # GET /history_administrative_groups
  # GET /history_administrative_groups.json
  def index
    @history_administrative_groups = HistoryAdministrativeGroup.all
  end

  # GET /history_administrative_groups/1
  # GET /history_administrative_groups/1.json
  def show
  end

  # GET /history_administrative_groups/new
  def new
    @history_administrative_group = HistoryAdministrativeGroup.new
    @student = params["student"] ? Student.find(params["student"].to_i) : nil
    if @student
      @history_administrative_group.student_id = @student.id
      @history_administrative_group.administrative_group_id = @student.last_administrative_group.administrative_group_id
    end
    @history_administrative_group.date_in = Date.today
  end

  # GET /history_administrative_groups/1/edit
  def edit
  end

  # POST /history_administrative_groups
  # POST /history_administrative_groups.json
  def create
    @history_administrative_group = HistoryAdministrativeGroup.new(history_administrative_group_params)

    respond_to do |format|
      if @history_administrative_group.save
        format.html { redirect_to @history_administrative_group.student, notice: 'History administrative group was successfully created.' }
        format.json { render :show, status: :created, location: @history_administrative_group }
      else
        format.html { render :new }
        format.json { render json: @history_administrative_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /history_administrative_groups/1
  # PATCH/PUT /history_administrative_groups/1.json
  def update
    respond_to do |format|
      if @history_administrative_group.update(history_administrative_group_params)
        format.html { redirect_to @history_administrative_group, notice: 'History administrative group was successfully updated.' }
        format.json { render :show, status: :ok, location: @history_administrative_group }
      else
        format.html { render :edit }
        format.json { render json: @history_administrative_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /history_administrative_groups/1
  # DELETE /history_administrative_groups/1.json
  def destroy
    @history_administrative_group.destroy
    respond_to do |format|
      format.html { redirect_to history_administrative_groups_url, notice: 'History administrative group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history_administrative_group
      @history_administrative_group = HistoryAdministrativeGroup.find(params[:id])
    end

    def set_groups
      @administrative_groups = AdministrativeGroup.order(:title)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_administrative_group_params
      params.require(:history_administrative_group).permit(:student_id, :administrative_group_id, :date_in, :date_out)
    end
end

app/helpers/history_administrative_groups_helper.rb
module HistoryAdministrativeGroupsHelper
end

app/views/history_administrative_groups/_form.html.erb
<%= form_for(@history_administrative_group) do |f| %>
  <% if @history_administrative_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history_administrative_group.errors.count, "error") %> prohibited this history_administrative_group from being saved:</h2>

      <ul>
      <% @history_administrative_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" hidden>
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id, readonly: true %>
  </div>
  <div class="control-group">
	  <div class="field input-group">
			<span class="input-group-addon" title="Nouveau groupe administratif"><i class="fa fa-university fa-fw"></i></span>
      <%= f.select(:administrative_group_id, [], {}, {class: "form-control"}) do %>
  			<% @administrative_groups.each do |group| %>
  				<%= content_tag(:option, group.title, value: group.id, selected: (group.id==@student[:administrative_group_id])) %>
  			<% end %>
  		<% end %>
    </div>
  </div>
  <div class="control-group">
			<div class="field input-group">
				<span class="input-group-addon" title="Date d'entrée"><i class="fa fa-calendar fa-fw"></i></span>
        <%= f.date_field :date_in, class: "form-control", value: @history_administrative_group.date_in.strftime("%d/%m/%Y") %>
      </div>
  </div>

  <div class="actions">
    <%= f.submit "Valider", class: "btn btn-primary" %> ou
    <%= link_to 'Annuler', :back %>
  </div>
<% end %>

app/views/history_administrative_groups/edit.html.erb
<h1>Editing History Administrative Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @history_administrative_group %> |
<%= link_to 'Back', history_administrative_groups_path %>

app/views/history_administrative_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing History Administrative Groups</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Student</th>
      <th>Administrative group</th>
      <th>Date in</th>
      <th>Date out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @history_administrative_groups.each do |history_administrative_group| %>
      <tr>
        <td><%= history_administrative_group.student.name %></td>
        <td><%= history_administrative_group.administrative_group.title %></td>
        <td><%= history_administrative_group.date_in.strftime("%d/%m/%Y") if history_administrative_group.date_in %></td>
        <td><%= history_administrative_group.date_out.strftime("%d/%m/%Y") if history_administrative_group.date_out %></td>
        <td><%= link_to 'Show', history_administrative_group %></td>
        <td><%= link_to 'Edit', edit_history_administrative_group_path(history_administrative_group) %></td>
        <td><%= link_to 'Destroy', history_administrative_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History administrative group', new_history_administrative_group_path %>

app/views/history_administrative_groups/new.html.erb
<div class="titre_actif">
  <h1><%= @student.name %><br/>Changement de groupe administratif</h1>
</div>

<%= render 'form' %>

app/views/history_administrative_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @history_administrative_group.student %>
</p>

<p>
  <strong>Administrative group:</strong>
  <%= @history_administrative_group.administrative_group %>
</p>

<p>
  <strong>Date in:</strong>
  <%= @history_administrative_group.date_in %>
</p>

<p>
  <strong>Date out:</strong>
  <%= @history_administrative_group.date_out %>
</p>

<%= link_to 'Edit', edit_history_administrative_group_path(@history_administrative_group) %> |
<%= link_to 'Back', history_administrative_groups_path %>