config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :caisses
  resources :group_coefficients
  resources :open_days
  resources :history_administrative_groups
  resources :history_physical_groups
  resources :absences
  resources :reasons
  resources :students
  get 'physical_groups/stats' => 'physical_groups#stats'
  get 'physical_groups/parameters' => 'group_coefficients#index'
  resources :physical_groups
  get 'physical_groups/:id/absences' => 'physical_groups#absences'
  get 'administrative_groups/stats' => 'administrative_groups#stats'
  get 'administrative_groups/parameters' => 'group_coefficients#index'
  get '/justifications' => 'justifications#index'
  resources :administrative_groups
  root 'presence#index'
  get 'about' => 'about#index'

  get 'today' => 'presence#absents_du_jour'
  get 'today_email' => 'presence#absents_du_jour_email'

  resource :user_sessions, only: [:create, :new, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/reason.rb
class Reason < ActiveRecord::Base
	has_many :absences
	validates :title, :presence => true
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)
    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reason_params
      params.require(:reason).permit(:title, :description, :absence)
    end
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<%= form_for(@reason) do |f| %>
  <% if @reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reason.errors.count, "error") %> prohibited this reason from being saved:</h2>

      <ul>
      <% @reason.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Titre" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon" title="Pensionnaire"><%= f.check_box :absence %></i></span>
      <div class="form-control">
        <%= f.label :absence do %>
          Considéré comme une absence ?
        <% end %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Valider", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<div class="titre_actif">
  <h1>Modifier une raison</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @reason %> |
<%= link_to 'Back', reasons_path %>

app/views/reasons/index.html.erb
<h1>Listing Reasons</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Absence ?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reasons.each do |reason| %>
      <tr>
        <td><%= reason.title %></td>
        <td><%= reason.description %></td>
        <td><%= reason.absence %></td>
        <td><%= link_to 'Show', reason %></td>
        <td><%= link_to 'Edit', edit_reason_path(reason) %></td>
        <td><%= link_to 'Destroy', reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reason', new_reason_path %>

app/views/reasons/new.html.erb
<div class="titre_actif">
  <h1>Nouvelle raison</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', reasons_path %>

app/views/reasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @reason.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reason.description %>
</p>

<%= link_to 'Edit', edit_reason_path(@reason) %> |
<%= link_to 'Back', reasons_path %>