config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :caisses
  resources :group_coefficients
  resources :open_days
  resources :history_administrative_groups
  resources :history_physical_groups
  resources :absences
  resources :reasons
  resources :students
  get 'physical_groups/stats' => 'physical_groups#stats'
  get 'physical_groups/parameters' => 'group_coefficients#index'
  resources :physical_groups
  get 'physical_groups/:id/absences' => 'physical_groups#absences'
  get 'administrative_groups/stats' => 'administrative_groups#stats'
  get 'administrative_groups/parameters' => 'group_coefficients#index'
  get '/justifications' => 'justifications#index'
  resources :administrative_groups
  root 'presence#index'
  get 'about' => 'about#index'

  get 'today' => 'presence#absents_du_jour'
  get 'today_email' => 'presence#absents_du_jour_email'

  resource :user_sessions, only: [:create, :new, :destroy]

  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/administrative_group.rb
class AdministrativeGroup < ActiveRecord::Base
	include ApplicationHelper
	has_many :absences
	has_many :students
	has_many :group_coefficients
	validates :title, :presence => true

	def number_of_students
		Student.where(administrative_group_id: self.id).count
	end

	def students_at(date)
    students = Student.joins(:history_administrative_groups)
                      .where("history_administrative_groups.administrative_group_id=? AND history_administrative_groups.date_in <= ? AND (history_administrative_groups.date_out >= ? OR history_administrative_groups.date_out IS NULL)",
                              self.id, date, date)
  end

	def nb_students_at(date)
		students_at(date).count
	end

	def nb_absences_at(month, year)
		date_deb = Date.parse("#{year}-#{month}-01")
		date_fin = date_deb + 1.month - 1.day
		nb = 0.0
		Absence.where(administrative_group_id: self.id, date: date_deb..date_fin, absence: true).each do |absence|
			if absence.morning and absence.afternoon
				nb += 1
			elsif absence.morning or absence.afternoon
				nb += 0.5 # Une absence de demi-journée est comptée comme entière ou moitié
			end
		end
		return nb
	end

	def nb_jours_prevus(date)
    open_days = OpenDay.where(year: date.year)
    nb_open_days = open_days.count>0 ? open_days.first[month_array_min_english[date.month-1]] : 0
    nb = 0
    students_at(date).each do |student|
      nb += nb_open_days * (student.coef.to_f>0.0 ? student.coef : self.coeff(date.year))
    end
    return nb
  end

	def coeff(year)
		return 0.9
	end

end

app/controllers/administrative_groups_controller.rb
class AdministrativeGroupsController < ApplicationController
  include ApplicationHelper
  before_action :set_administrative_group, only: [:show, :edit, :update, :destroy]
  before_action :set_year, only: [:stats, :parameters]

  # GET /administrative_groups
  # GET /administrative_groups.json
  def index
    @administrative_groups = AdministrativeGroup.all
    @graph_nb_eleve = []
    @administrative_groups.each do |ag|
      @graph_nb_eleve << [ag.title, ag.number_of_students]
    end
  end

  def stats
    @administrative_groups = AdministrativeGroup.all
    @nb_open_days = OpenDay.where(year: @year).first

    @graph = []
    @administrative_groups.each do |group|
      graph_month = []
      (1..12).to_a.each do |month|
        mois = month_array_min_english[month-1]
        nb_open_days = @nb_open_days ? @nb_open_days[mois] : 0
        date = Date.parse("#{@year}-#{month}-01")+1.month-1.day
        nb_max = group.nb_students_at(date)*nb_open_days
        nb_prevue = group.nb_jours_prevus(date).round(0)
        nb_realisee = nb_max - group.nb_absences_at(month, @year)
        ecart = nb_realisee - nb_prevue
        pourc = nb_realisee*100/nb_max
        if (Date.parse("#{@year}-#{month}-1") + 1.month - 1.day) > Date.today
          graph_month << [month_array[month-1], 0]
        else
          graph_month << [month_array[month-1], ecart]
        end
      end
      @graph << {name: group.title, data: graph_month}
    end
  end

  def parameters
    @administrative_groups = AdministrativeGroup.all
    @open_days = OpenDay.where(year: @year).first
  end

  # GET /administrative_groups/1
  # GET /administrative_groups/1.json
  def show
    @students = Student.where(administrative_group_id: @administrative_group.id).order(:last_name, :first_name)
    @graph_age = {}
    @students.each do |student|
      @graph_age[student.age] = @graph_age[student.age].to_i + 1
    end
  end

  # GET /administrative_groups/new
  def new
    @administrative_group = AdministrativeGroup.new
  end

  # GET /administrative_groups/1/edit
  def edit
  end

  # POST /administrative_groups
  # POST /administrative_groups.json
  def create
    @administrative_group = AdministrativeGroup.new(administrative_group_params)

    respond_to do |format|
      if @administrative_group.save
        format.html { redirect_to @administrative_group, notice: 'Administrative group was successfully created.' }
        format.json { render :show, status: :created, location: @administrative_group }
      else
        format.html { render :new }
        format.json { render json: @administrative_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrative_groups/1
  # PATCH/PUT /administrative_groups/1.json
  def update
    respond_to do |format|
      if @administrative_group.update(administrative_group_params)
        format.html { redirect_to @administrative_group, notice: 'Administrative group was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrative_group }
      else
        format.html { render :edit }
        format.json { render json: @administrative_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrative_groups/1
  # DELETE /administrative_groups/1.json
  def destroy
    @administrative_group.destroy
    respond_to do |format|
      format.html { redirect_to administrative_groups_url, notice: 'Administrative group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrative_group
      @administrative_group = AdministrativeGroup.find(params[:id])
    end

    def set_year
      @year = params["year"] ? params["year"].to_i : Date.today.year
      @year = Date.today.year if @year > Date.today.year
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrative_group_params
      params.require(:administrative_group).permit(:title, :description)
    end
end

app/helpers/administrative_groups_helper.rb
module AdministrativeGroupsHelper
end

app/views/administrative_groups/_form.html.erb
<%= form_for(@administrative_group) do |f| %>
  <% if @administrative_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrative_group.errors.count, "error") %> prohibited this administrative_group from being saved:</h2>

      <ul>
      <% @administrative_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon" title="Titre"><i class="fa fa-pencil fa-fw"></i></span>
      <%= f.text_field :title, class:"form-control" %>
    </div>
  </div>
  <div class="control-group">
    <div class="field input-group">
      <span class="input-group-addon" title="Description"><i class="fa fa-pencil-square-o fa-fw"></i></span>
      <%= f.text_area :description, class:"form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Valider", class: "btn btn-primary" %> ou
    <%= link_to 'Annuler', :back %> 
  </div>
<% end %>

app/views/administrative_groups/_header.html.erb
<p id="notice"><%= notice %></p>

<div class="titre_actif">
  <h1>Groupes administratifs</h1>
</div>

<div class="profile-usermenu-horizontal">
  <ul>
    <li class="<%= (request.original_fullpath=="/administrative_groups" ? 'active' : '') %>">
      <a href="/administrative_groups">
      <i class="fa fa-university"></i>
      Groupes</a>
    </li>
    <li class="<%= (request.original_fullpath.include?("/administrative_groups/stats")  ? 'active' : '') %>">
      <a href="/administrative_groups/stats">
      <i class="fa fa-line-chart"></i>
      Statistiques </a>
    </li>
  </ul>
</div>

app/views/administrative_groups/edit.html.erb
<div class="titre_actif">
  <h1><%= @administrative_group.title %></h1>
</div>

<%= render 'form' %>

app/views/administrative_groups/index.html.erb
<%= render "header" %>

<div class="cadre_bleu">
  <h2>Groupes :</h2>
</div>

<div id="toolbar1">
  <%= link_to 'Créer un nouveau groupe', new_administrative_group_path, class: "btn btn-primary" %>
</div>

<table id="table1"
  data-toolbar="#toolbar1"
  data-search="true"
  data-show-columns="true"
  data-show-export="true"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-page-list="[10, 25, 50, 100, ALL]"
  data-show-footer="false"
  data-toggle="table">
  <thead>
    <tr>
      <th data-align="left" data-valign="middle">Sigle</th>
      <th data-align="center" data-valign="middle">Description</th>
      <th data-align="center" data-valign="middle">Nombre d'usagers</th>
    </tr>
  </thead>
  <tbody>
    <% @administrative_groups.each do |administrative_group| %>
      <tr>
        <td><%= link_to administrative_group.title, administrative_group %></td>
        <td><%= administrative_group.description %></td>
        <td><%= administrative_group.number_of_students %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="cadre_bleu">
  <h2> Nombre d'usagers :</h2>
</div>

<%= column_chart @graph_nb_eleve %>

app/views/administrative_groups/new.html.erb
<div class="titre_actif">
  <h1>Nouveau groupe administratif</h1>
</div>

<%= render 'form' %>

app/views/administrative_groups/parameters.html.erb
<%= render "header" %>

<br/><br/>

<div class="field input-group">
	<span class="input-group-addon">
    <%= link_to "/administrative_groups/parameters?year=#{@year-1}" do %>
      <i class="fa fa-arrow-left fa-fw"></i>
    <% end %>
  </span>
	<p align="center" class="form-control"><%= @year %></p>
	<% if @year<Date.today.year %>
    <span class="input-group-addon">
      <%= link_to "/administrative_groups/parameters?year=#{@year+1}" do %>
        <i class="fa fa-arrow-right fa-fw"></i>
      <% end %>
    </span>
	<% end %>
</div>

<div class="cadre_bleu">
  <h2>Nombre de jours ouvrés :</h2>
</div>

<div class="table-responsive table-larger">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><%= @year %></th>
        <% month_array_min.each do |month| %>
          <th><%= month %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to "modifier", @open_days ? edit_open_day_path(@open_days) : new_open_day_path(year: @year), class: "btn btn-primary btn-xs" %></td>
        <% month_array_min_english.each do |month| %>
          <td><%= @open_days ? @open_days[month] : "-" %></td>
        <% end %>
      </tr>

    </tbody>
  </table>
</div>

app/views/administrative_groups/show.html.erb
<p id="notice"><%= notice %></p>

<div class="titre_actif">
  <h1><%= @administrative_group.title %></h1>
</div>




<div class="cadre_bleu">
  <h2>Usagers :</h2>
</div>

<div id="toolbar1">
  <%= link_to 'Ajouter un usager', new_student_path(administrative_group: @administrative_group.id), class: "btn btn-primary" %>
</div>

<table id="table1"
  data-toolbar="#toolbar1"
  data-search="true"
  data-show-columns="true"
  data-show-export="true"
  data-show-pagination-switch="true"
  data-pagination="true"
  data-page-list="[10, 25, 50, 100, ALL]"
  data-show-footer="false"
  data-toggle="table">
  <thead>
    <tr>
      <th data-align="left" data-valign="middle">Nom et prénom</th>
      <th data-align="center" data-valign="middle">Date de naissance</th>
      <th data-align="center" data-valign="middle">Age</th>
      <th data-align="center" data-valign="middle">Date d'entrée</th>
      <th data-align="center" data-valign="middle">Pensionnaire</th>
      <th></th>
    </tr>
  </thead>  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student %></td>
        <td><%= student.birth_date.strftime("%d/%m/%Y") if student.birth_date %></td>
        <td><%= student.age %></td>
        <td><%= student.last_administrative_group.date_in.strftime("%d/%m/%Y") if student.last_administrative_group %></td>
        <% if student.roomer %>
          <td><i class="fa fa-bed fa-fw"></i></td>
        <% else %>
          <td>-</td>
        <% end %>
        <td>
          <%= link_to edit_student_path(student) do %>
            <i class="fa fa-pencil fa-fw"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="cadre_bleu">
  <h2>Tranche d'âge des usagers :</h2>
</div>

<%= column_chart @graph_age %>

app/views/administrative_groups/stats.html.erb
<%= render "header" %>

<div class="cadre_bleu">
  <h2>Statistiques :</h2>
</div>

<div class="field input-group">
	<span class="input-group-addon">
    <%= link_to "/administrative_groups/stats?year=#{@year-1}" do %>
      <i class="fa fa-arrow-left fa-fw"></i>
    <% end %>
  </span>
	<p align="center" class="form-control"><%= @year %></p>
	<% if @year<Date.today.year %>
    <span class="input-group-addon">
      <%= link_to "/administrative_groups/stats?year=#{@year+1}" do %>
        <i class="fa fa-arrow-right fa-fw"></i>
      <% end %>
    </span>
	<% end %>
</div>

<div>
  <table id="table1"
    data-toolbar="#toolbar1"
    data-search="true"
    data-show-columns="false"
    data-show-export="true"
    data-show-pagination-switch="false"
    data-pagination="false"
    data-page-list="[10, 25, 50, 100, ALL]"
    data-show-footer="false"
    data-toggle="table">
    <thead>
      <tr>
        <th><%= @year %></th>
        <% month_array.each do |month| %>
          <th colspan="3"><%= month %></th>
        <% end %>
        <th class="cell-mini">TOTAL</th>
        <th class="cell-mini">Journées ou actes à réaliser</th>
        <th class="cell-mini">Différentiel</th>
      </tr>
      <tr>
        <th class="cell-mini">
          Nb jours ouv/mois
          <%= link_to @nb_open_days ? edit_open_day_path(@nb_open_days) : new_open_day_path(year: @year) do %>
            <i class="fa fa-pencil fa-2x"></i>
          <% end %>
        </th>
        <% month_array_min_english.each do |month| %>
          <th colspan="3" class="cell-mini">
            <%= @nb_open_days ? @nb_open_days[month] : "-" %>
          </th>
        <% end %>
      </tr>
      <tr>
        <th class="cell-mini">Nb jours</th>
        <% month_array_min.each do |month| %>
          <th class="cell-mini">réalisés</th>
          <th class="cell-mini">prévus</th>
          <th class="cell-mini">écart</th>
        <% end %>
        <th>-</th>
        <th>-</th>
        <th>-</th>
      </tr>
    </thead>
    <tbody>
      <% totaux_month = {"realises" => {}, "prevus" => {}} %>
      <% @administrative_groups.each do |group| %>
        <tr>
          <td colspan="2"><%= group.title %></td>
          <% totaux = {} %>
          <% (1..12).to_a.each do |month| %>
            <% nb_open_days = @nb_open_days ? @nb_open_days[month_array_min_english[month-1]] : 0 %>
            <% date = Date.parse("#{@year}-#{month}-01")+1.month-1.day %>
            <% nb_max = group.nb_students_at(date)*nb_open_days %>
            <% nb_prevue = group.nb_jours_prevus(date).round(0) %>
            <% nb_realisee = (nb_max - group.nb_absences_at(month, @year)).round(0) %>
            <% totaux["realises"] = totaux["realises"].to_i + nb_realisee %>
            <% totaux["prevus"] = totaux["prevus"].to_i + nb_prevue %>
            <% totaux_month["realises"][month] = totaux_month["realises"][month].to_i + nb_realisee %>
            <% totaux_month["realises"]["global"] = totaux_month["realises"]["global"].to_i + nb_realisee %>
            <% totaux_month["prevus"][month] = totaux_month["prevus"][month].to_i + nb_prevue %>
            <% totaux_month["prevus"]["global"] = totaux_month["prevus"]["global"].to_i + nb_prevue %>
            <% p totaux_month %>
            <% if (Date.parse("#{@year}-#{month}-1")+1.month-1.day) > Date.today %>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            <% else %>
              <td>
                <%= @nb_open_days ? nb_realisee : "-" %>
              </td>
              <td>
                <%= @nb_open_days ? nb_prevue : "-" %>
              </td>
              <td>
                <%= @nb_open_days ? nb_realisee - nb_prevue : "-" %>
              </td>
            <% end %>
          <% end %>
          <td><%= totaux["realises"] %></td>
          <td><%= totaux["prevus"] %></td>
          <td><%= totaux["realises"] - totaux["prevus"] %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">Total journées</td>
        <% (1..12).to_a.each do |month| %>
          <td><%= totaux_month["realises"][month]%></td>
          <td><%= totaux_month["prevus"][month]%></td>
          <td><%= totaux_month["realises"][month].to_i - totaux_month["prevus"][month].to_i %></td>
        <% end %>
        <td><%= totaux_month["realises"]["global"]%></td>
        <td><%= totaux_month["prevus"]["global"]%></td>
        <td><%= totaux_month["realises"]["global"].to_i - totaux_month["prevus"]["global"].to_i %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= column_chart @graph, id: "graph" %>